version: '3.9'
services:
  php-fpm:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
      args:
        - "USER_ID=$uid"
        - "GROUP_ID=$gid"
        - "OSTYPE=$ostype"
        - "USERNAME=$USER"
        - "APP_ENV=loc"
    environment:
      TERMINAL_EMULATOR: JetBrains-JediTerm
    volumes:
      - "../code:/code"
    restart: always
    user: 1000:1000
    networks:
      - testing-se

  nginx:
    image: nginx:1.23-alpine
    depends_on:
      - php-fpm
    volumes:
      - "../code:/code"
      - "../docker/nginx/configs/conf.d:/etc/nginx/conf.d"
      - "../docker/nginx/configs/ssl:/etc/nginx/ssl"
    ports:
      - "80:80"
    restart: always
    networks:
      - testing-se

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'local_db'
    ports:
      - "3306:3306"
    restart: always
    networks:
      - testing-se

  mysql-test:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test_db'
    ports:
      - "3307:3306"
    restart: always
    networks:
      - testing-se

networks:
  testing-se:
    name: testing-se
